"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Fab(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_STR_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    hash_str: builtins.str
    """This field is the hash of the data field. It is used to identify the data.
    The hash is calculated using the SHA-256 algorithm and is represented as a
    hex string (sha256hex).
    """
    content: builtins.bytes
    """This field contains the fab file contents a one bytes blob."""
    def __init__(
        self,
        *,
        hash_str: builtins.str = ...,
        content: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "hash_str", b"hash_str"]) -> None: ...

global___Fab = Fab

@typing.final
class GetFabRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_STR_FIELD_NUMBER: builtins.int
    hash_str: builtins.str
    def __init__(
        self,
        *,
        hash_str: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hash_str", b"hash_str"]) -> None: ...

global___GetFabRequest = GetFabRequest

@typing.final
class GetFabResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FAB_FIELD_NUMBER: builtins.int
    @property
    def fab(self) -> global___Fab: ...
    def __init__(
        self,
        *,
        fab: global___Fab | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fab", b"fab"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fab", b"fab"]) -> None: ...

global___GetFabResponse = GetFabResponse
