"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2022 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.error_pb2
import flwr.proto.node_pb2
import flwr.proto.recordset_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCER_FIELD_NUMBER: builtins.int
    CONSUMER_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    DELIVERED_AT_FIELD_NUMBER: builtins.int
    PUSHED_AT_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    ANCESTRY_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    RECORDSET_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    created_at: builtins.float
    delivered_at: builtins.str
    pushed_at: builtins.float
    ttl: builtins.float
    task_type: builtins.str
    @property
    def producer(self) -> flwr.proto.node_pb2.Node: ...
    @property
    def consumer(self) -> flwr.proto.node_pb2.Node: ...
    @property
    def ancestry(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def recordset(self) -> flwr.proto.recordset_pb2.RecordSet: ...
    @property
    def error(self) -> flwr.proto.error_pb2.Error: ...
    def __init__(
        self,
        *,
        producer: flwr.proto.node_pb2.Node | None = ...,
        consumer: flwr.proto.node_pb2.Node | None = ...,
        created_at: builtins.float = ...,
        delivered_at: builtins.str = ...,
        pushed_at: builtins.float = ...,
        ttl: builtins.float = ...,
        ancestry: collections.abc.Iterable[builtins.str] | None = ...,
        task_type: builtins.str = ...,
        recordset: flwr.proto.recordset_pb2.RecordSet | None = ...,
        error: flwr.proto.error_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["consumer", b"consumer", "error", b"error", "producer", b"producer", "recordset", b"recordset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ancestry", b"ancestry", "consumer", b"consumer", "created_at", b"created_at", "delivered_at", b"delivered_at", "error", b"error", "producer", b"producer", "pushed_at", b"pushed_at", "recordset", b"recordset", "task_type", b"task_type", "ttl", b"ttl"]) -> None: ...

global___Task = Task

@typing.final
class TaskIns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TASK_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    group_id: builtins.str
    run_id: builtins.int
    @property
    def task(self) -> global___Task: ...
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        group_id: builtins.str = ...,
        run_id: builtins.int = ...,
        task: global___Task | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["group_id", b"group_id", "run_id", b"run_id", "task", b"task", "task_id", b"task_id"]) -> None: ...

global___TaskIns = TaskIns

@typing.final
class TaskRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TASK_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    group_id: builtins.str
    run_id: builtins.int
    @property
    def task(self) -> global___Task: ...
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        group_id: builtins.str = ...,
        run_id: builtins.int = ...,
        task: global___Task | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["group_id", b"group_id", "run_id", b"run_id", "task", b"task", "task_id", b"task_id"]) -> None: ...

global___TaskRes = TaskRes
