defaults = ["_self_", {"override hydra/hydra_logging" = "disabled"}, {"override hydra/job_logging" = "disabled"}]
store = true
plot = true
csv = true
num_clients = 8
num_rounds = 5
wandb_mode = "offline"
wandb_project = "MIA"
mitigation = false
dp = false
laplace = false
epsilon = 5
delta = 0.0001
clip_threshold = 0.5
sigma = 1
embedding_dim = 8
hidden_dim = 100
num_layers = 2
seq_length = 80
vocab_size = 80
text_label = "target"
text_input = "input"
n_convlayers = [64, 64, 128]
kernel_sizes = [3, 3, 5]
n_linearlayers = [100, 10]
momentum = 0.9
w_decay = 1e-05
pool_size = 2
dataset = "cifar10"
image_name = "img"
image_label = "label"
num_classes = 10
local_dataset = true
path_to_local_dataset = "../data/cifar10/"
input_size = 32
experiments_track_folder = "./experiments_ids/"
use_fedprox = false
proximal_mu = 0.1
lr = 0.01
lr_epochs = [150, 225]
batch_size = 64
batch_size_subset = 4
zscore_threshold = 1
architecture = "AlexNet"
local_epochs = 1
power = 1
multiplicator = 1
iid = true
dirichlet_alpha = 0.5
average_detection = 1
initial_l = 1.0
attack_constant = 0.1
noise_fraction = 0.2
canary = false
canary_epochs = 5
dynamic_canary = true
single_training = false
noise = false
canary_batch_size = 16
freerider_canary = false
yeom_type = "serverside"
server_epochs = 2
orthogonality_th = 0.0005
average_rounds = 10
num_freeriders = 1
freerider_type = "advanced_disguised"
subset_samples = 32
train_samples = 4000
test_samples = 1000
metric = "loss"
attack_types = ["dagmm"]
pia_type = "old"
gamma = 0.5
name_layer_grads = "None"
std = 0.0001
n_encoder_layers = [128, 64, 32]
n_gmm_layers = [10, 10, 2]
dagmm_batch_size = 16
dagmm_epochs = 100
enable_offsets = false
sample_per_label = 20
decaf_batch_size = 32
