# Uses a pre-built image from nvidia

# check this repo to learn more about the image below: https://github.com/dusty-nv/jetson-containers
FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3

RUN mkdir /app
WORKDIR /app

RUN echo "done!"
