"""Generate plots from json files."""

import json
import os
from typing import List, Tuple

import matplotlib.pyplot as plt


def read_from_results(path) -> Tuple[str, str, List]:
    """Load the json file with recorded configurations and results."""
    with open(path, "r") as fin:
        data = json.load(fin)
        algorithm = data["run_config"]["algorithm"]
        model = data["run_config"]["model-name"]
        accuracies = [res["accuracy"] * 100 for res in data["round_res"]]
        return algorithm, model, accuracies


def make_plot(dir_path, plt_title) -> None:
    """Given a directory with json files, generated a plot using the provided title."""
    plt.figure()
    with os.scandir(dir_path) as files:
        for file in files:
            algo, m, acc = read_from_results(file)
            rounds = [i + 1 for i in range(len(acc))]
            print(f"Max accuracy ({algo}): {max(acc):.2f}")
            plt.plot(rounds, acc, label=algo)
    plt.xlabel("Rounds")
    plt.ylabel("Accuracy")
    plt.title(plt_title)
    plt.grid()
    plt.legend()
    plt.savefig(plt_title)


if __name__ == "__main__":
    # Plot results generated by the baseline.
    directory = "../results/"
    title = "FedRep"
    make_plot(directory, plt_title=title)
