# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flower/proto/transport.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flower/proto/transport.proto',
  package='flower.transport',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1c\x66lower/proto/transport.proto\x12\x10\x66lower.transport\"\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\"5\n\x07Weights\x12*\n\x07weights\x18\x01 \x03(\x0b\x32\x19.flower.transport.NDArray\"\xa2\x03\n\rServerMessage\x12>\n\treconnect\x18\x01 \x01(\x0b\x32).flower.transport.ServerMessage.ReconnectH\x00\x12\x41\n\x0bget_weights\x18\x02 \x01(\x0b\x32*.flower.transport.ServerMessage.GetWeightsH\x00\x12\x32\n\x03\x66it\x18\x03 \x01(\x0b\x32#.flower.transport.ServerMessage.FitH\x00\x12<\n\x08\x65valuate\x18\x04 \x01(\x0b\x32(.flower.transport.ServerMessage.EvaluateH\x00\x1a\x1c\n\tReconnect\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x1a\x0c\n\nGetWeights\x1a\x31\n\x03\x46it\x12*\n\x07weights\x18\x01 \x01(\x0b\x32\x19.flower.transport.Weights\x1a\x36\n\x08\x45valuate\x12*\n\x07weights\x18\x01 \x01(\x0b\x32\x19.flower.transport.WeightsB\x05\n\x03msg\"\xf8\x03\n\rClientMessage\x12@\n\ndisconnect\x18\x01 \x01(\x0b\x32*.flower.transport.ClientMessage.DisconnectH\x00\x12\x41\n\x0bget_weights\x18\x02 \x01(\x0b\x32*.flower.transport.ClientMessage.GetWeightsH\x00\x12\x32\n\x03\x66it\x18\x03 \x01(\x0b\x32#.flower.transport.ClientMessage.FitH\x00\x12<\n\x08\x65valuate\x18\x04 \x01(\x0b\x32(.flower.transport.ClientMessage.EvaluateH\x00\x1a\x36\n\nDisconnect\x12(\n\x06reason\x18\x01 \x01(\x0e\x32\x18.flower.transport.Reason\x1a\x38\n\nGetWeights\x12*\n\x07weights\x18\x01 \x01(\x0b\x32\x19.flower.transport.Weights\x1aG\n\x03\x46it\x12*\n\x07weights\x18\x01 \x01(\x0b\x32\x19.flower.transport.Weights\x12\x14\n\x0cnum_examples\x18\x02 \x01(\x03\x1a.\n\x08\x45valuate\x12\x14\n\x0cnum_examples\x18\x01 \x01(\x03\x12\x0c\n\x04loss\x18\x02 \x01(\x02\x42\x05\n\x03msg*E\n\x06Reason\x12\r\n\tRECONNECT\x10\x00\x12\x16\n\x12POWER_DISCONNECTED\x10\x01\x12\x14\n\x10WIFI_UNAVAILABLE\x10\x02\x32_\n\rFlowerService\x12N\n\x04Join\x12\x1f.flower.transport.ClientMessage\x1a\x1f.flower.transport.ServerMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)

_REASON = _descriptor.EnumDescriptor(
  name='Reason',
  full_name='flower.transport.Reason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECONNECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER_DISCONNECTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIFI_UNAVAILABLE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1061,
  serialized_end=1130,
)
_sym_db.RegisterEnumDescriptor(_REASON)

Reason = enum_type_wrapper.EnumTypeWrapper(_REASON)
RECONNECT = 0
POWER_DISCONNECTED = 1
WIFI_UNAVAILABLE = 2



_NDARRAY = _descriptor.Descriptor(
  name='NDArray',
  full_name='flower.transport.NDArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='flower.transport.NDArray.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=76,
)


_WEIGHTS = _descriptor.Descriptor(
  name='Weights',
  full_name='flower.transport.Weights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='flower.transport.Weights.weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=131,
)


_SERVERMESSAGE_RECONNECT = _descriptor.Descriptor(
  name='Reconnect',
  full_name='flower.transport.ServerMessage.Reconnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='flower.transport.ServerMessage.Reconnect.seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=424,
)

_SERVERMESSAGE_GETWEIGHTS = _descriptor.Descriptor(
  name='GetWeights',
  full_name='flower.transport.ServerMessage.GetWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=438,
)

_SERVERMESSAGE_FIT = _descriptor.Descriptor(
  name='Fit',
  full_name='flower.transport.ServerMessage.Fit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='flower.transport.ServerMessage.Fit.weights', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=489,
)

_SERVERMESSAGE_EVALUATE = _descriptor.Descriptor(
  name='Evaluate',
  full_name='flower.transport.ServerMessage.Evaluate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='flower.transport.ServerMessage.Evaluate.weights', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=545,
)

_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='flower.transport.ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reconnect', full_name='flower.transport.ServerMessage.reconnect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_weights', full_name='flower.transport.ServerMessage.get_weights', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fit', full_name='flower.transport.ServerMessage.fit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evaluate', full_name='flower.transport.ServerMessage.evaluate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERVERMESSAGE_RECONNECT, _SERVERMESSAGE_GETWEIGHTS, _SERVERMESSAGE_FIT, _SERVERMESSAGE_EVALUATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='flower.transport.ServerMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=134,
  serialized_end=552,
)


_CLIENTMESSAGE_DISCONNECT = _descriptor.Descriptor(
  name='Disconnect',
  full_name='flower.transport.ClientMessage.Disconnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='flower.transport.ClientMessage.Disconnect.reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=819,
  serialized_end=873,
)

_CLIENTMESSAGE_GETWEIGHTS = _descriptor.Descriptor(
  name='GetWeights',
  full_name='flower.transport.ClientMessage.GetWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='flower.transport.ClientMessage.GetWeights.weights', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=875,
  serialized_end=931,
)

_CLIENTMESSAGE_FIT = _descriptor.Descriptor(
  name='Fit',
  full_name='flower.transport.ClientMessage.Fit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='flower.transport.ClientMessage.Fit.weights', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_examples', full_name='flower.transport.ClientMessage.Fit.num_examples', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=933,
  serialized_end=1004,
)

_CLIENTMESSAGE_EVALUATE = _descriptor.Descriptor(
  name='Evaluate',
  full_name='flower.transport.ClientMessage.Evaluate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_examples', full_name='flower.transport.ClientMessage.Evaluate.num_examples', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loss', full_name='flower.transport.ClientMessage.Evaluate.loss', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1006,
  serialized_end=1052,
)

_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='flower.transport.ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='flower.transport.ClientMessage.disconnect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_weights', full_name='flower.transport.ClientMessage.get_weights', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fit', full_name='flower.transport.ClientMessage.fit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evaluate', full_name='flower.transport.ClientMessage.evaluate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTMESSAGE_DISCONNECT, _CLIENTMESSAGE_GETWEIGHTS, _CLIENTMESSAGE_FIT, _CLIENTMESSAGE_EVALUATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='flower.transport.ClientMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=555,
  serialized_end=1059,
)

_WEIGHTS.fields_by_name['weights'].message_type = _NDARRAY
_SERVERMESSAGE_RECONNECT.containing_type = _SERVERMESSAGE
_SERVERMESSAGE_GETWEIGHTS.containing_type = _SERVERMESSAGE
_SERVERMESSAGE_FIT.fields_by_name['weights'].message_type = _WEIGHTS
_SERVERMESSAGE_FIT.containing_type = _SERVERMESSAGE
_SERVERMESSAGE_EVALUATE.fields_by_name['weights'].message_type = _WEIGHTS
_SERVERMESSAGE_EVALUATE.containing_type = _SERVERMESSAGE
_SERVERMESSAGE.fields_by_name['reconnect'].message_type = _SERVERMESSAGE_RECONNECT
_SERVERMESSAGE.fields_by_name['get_weights'].message_type = _SERVERMESSAGE_GETWEIGHTS
_SERVERMESSAGE.fields_by_name['fit'].message_type = _SERVERMESSAGE_FIT
_SERVERMESSAGE.fields_by_name['evaluate'].message_type = _SERVERMESSAGE_EVALUATE
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['reconnect'])
_SERVERMESSAGE.fields_by_name['reconnect'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['get_weights'])
_SERVERMESSAGE.fields_by_name['get_weights'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['fit'])
_SERVERMESSAGE.fields_by_name['fit'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['evaluate'])
_SERVERMESSAGE.fields_by_name['evaluate'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE_DISCONNECT.fields_by_name['reason'].enum_type = _REASON
_CLIENTMESSAGE_DISCONNECT.containing_type = _CLIENTMESSAGE
_CLIENTMESSAGE_GETWEIGHTS.fields_by_name['weights'].message_type = _WEIGHTS
_CLIENTMESSAGE_GETWEIGHTS.containing_type = _CLIENTMESSAGE
_CLIENTMESSAGE_FIT.fields_by_name['weights'].message_type = _WEIGHTS
_CLIENTMESSAGE_FIT.containing_type = _CLIENTMESSAGE
_CLIENTMESSAGE_EVALUATE.containing_type = _CLIENTMESSAGE
_CLIENTMESSAGE.fields_by_name['disconnect'].message_type = _CLIENTMESSAGE_DISCONNECT
_CLIENTMESSAGE.fields_by_name['get_weights'].message_type = _CLIENTMESSAGE_GETWEIGHTS
_CLIENTMESSAGE.fields_by_name['fit'].message_type = _CLIENTMESSAGE_FIT
_CLIENTMESSAGE.fields_by_name['evaluate'].message_type = _CLIENTMESSAGE_EVALUATE
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['disconnect'])
_CLIENTMESSAGE.fields_by_name['disconnect'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['get_weights'])
_CLIENTMESSAGE.fields_by_name['get_weights'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['fit'])
_CLIENTMESSAGE.fields_by_name['fit'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['evaluate'])
_CLIENTMESSAGE.fields_by_name['evaluate'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['NDArray'] = _NDARRAY
DESCRIPTOR.message_types_by_name['Weights'] = _WEIGHTS
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.enum_types_by_name['Reason'] = _REASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'flower.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:flower.transport.NDArray)
  })
_sym_db.RegisterMessage(NDArray)

Weights = _reflection.GeneratedProtocolMessageType('Weights', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHTS,
  '__module__' : 'flower.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:flower.transport.Weights)
  })
_sym_db.RegisterMessage(Weights)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {

  'Reconnect' : _reflection.GeneratedProtocolMessageType('Reconnect', (_message.Message,), {
    'DESCRIPTOR' : _SERVERMESSAGE_RECONNECT,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ServerMessage.Reconnect)
    })
  ,

  'GetWeights' : _reflection.GeneratedProtocolMessageType('GetWeights', (_message.Message,), {
    'DESCRIPTOR' : _SERVERMESSAGE_GETWEIGHTS,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ServerMessage.GetWeights)
    })
  ,

  'Fit' : _reflection.GeneratedProtocolMessageType('Fit', (_message.Message,), {
    'DESCRIPTOR' : _SERVERMESSAGE_FIT,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ServerMessage.Fit)
    })
  ,

  'Evaluate' : _reflection.GeneratedProtocolMessageType('Evaluate', (_message.Message,), {
    'DESCRIPTOR' : _SERVERMESSAGE_EVALUATE,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ServerMessage.Evaluate)
    })
  ,
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'flower.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:flower.transport.ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)
_sym_db.RegisterMessage(ServerMessage.Reconnect)
_sym_db.RegisterMessage(ServerMessage.GetWeights)
_sym_db.RegisterMessage(ServerMessage.Fit)
_sym_db.RegisterMessage(ServerMessage.Evaluate)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {

  'Disconnect' : _reflection.GeneratedProtocolMessageType('Disconnect', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTMESSAGE_DISCONNECT,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ClientMessage.Disconnect)
    })
  ,

  'GetWeights' : _reflection.GeneratedProtocolMessageType('GetWeights', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTMESSAGE_GETWEIGHTS,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ClientMessage.GetWeights)
    })
  ,

  'Fit' : _reflection.GeneratedProtocolMessageType('Fit', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTMESSAGE_FIT,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ClientMessage.Fit)
    })
  ,

  'Evaluate' : _reflection.GeneratedProtocolMessageType('Evaluate', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTMESSAGE_EVALUATE,
    '__module__' : 'flower.proto.transport_pb2'
    # @@protoc_insertion_point(class_scope:flower.transport.ClientMessage.Evaluate)
    })
  ,
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'flower.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:flower.transport.ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)
_sym_db.RegisterMessage(ClientMessage.Disconnect)
_sym_db.RegisterMessage(ClientMessage.GetWeights)
_sym_db.RegisterMessage(ClientMessage.Fit)
_sym_db.RegisterMessage(ClientMessage.Evaluate)



_FLOWERSERVICE = _descriptor.ServiceDescriptor(
  name='FlowerService',
  full_name='flower.transport.FlowerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=1132,
  serialized_end=1227,
  methods=[
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='flower.transport.FlowerService.Join',
    index=0,
    containing_service=None,
    input_type=_CLIENTMESSAGE,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLOWERSERVICE)

DESCRIPTOR.services_by_name['FlowerService'] = _FLOWERSERVICE

# @@protoc_insertion_point(module_scope)
