{
 "title": "Dashboard Index",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Client1 - Cumulative count of packets received\t",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_network_receive_packets_total{name=\"client1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client1 - Cumulative count of packets transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "container_network_transmit_packets_total{name=\"client1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client1 - Cumulative cpu time consumed in seconds",
   "type": "barchart",
   "description": "The total amount of time that the CPU has spent executing a specific process or set of processes.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"client1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client1 - Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"client1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server - Cumulative cpu time consumed in seconds",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server - Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server - Model Loss",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "model_loss{instance=\"server:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server - Model Accuracy",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "model_accuracy{instance=\"server:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}