random_seed: 42

learning_rate: 0.001

model_type: 'Pytorch'
model:
  _target_: fedopsmnist.models.MNISTClassifier
  output_size: 10

dataset:
  name: 'MNIST'
  validation_split: 0.2

task_id: 'task_id'

wandb:
  use: false
  key: 'your wandb api key'
  account: 'your wandb account'
  project: '${dataset.name}_${task_id}'

num_epochs: 1
batch_size: 128
num_rounds: 2
clients_per_round: 1

server:
  strategy:
    _target_: flwr.server.strategy.FedAvg
    fraction_fit: 0.00001
    fraction_evaluate: 0.000001
    min_fit_clients: ${clients_per_round}
    min_available_clients: ${clients_per_round}
    min_evaluate_clients: ${clients_per_round}
