class SharedFolder:
    def get(self, key, default=None):
        ...

    def __getitem__(self, key):
        ...

    def __setitem__(self, key, value):
        ...

    def __len__(self):
        ...

    def items(self):
        ...
