# For now we have decided to disable this workflow as many of the baselines are
# not being actively maintained and we don't want to block PRs that touch
# multiple baselines. We will revisit this in the future when we have a better
# idea of how to maintain the baselines and ensure they are up to date.

name: Baselines

on:
  workflow_dispatch:

jobs:
  no-op:
    runs-on: ubuntu-22.04
    if: ${{ false }}
    steps:
      - run: echo "disabled"
